---
- name: Setup Frontend Server
  hosts: frontend
  become: yes
  vars:
    app_dir: /home/ec2-user/pokeapi-frontend
    
  tasks:
    - name: Wait for instance to be ready
      wait_for_connection:
        timeout: 300

    - name: Install required packages
      yum:
        name:
          - git
          - python3
          - python3-pip
        state: present

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Clone repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_dir }}"
        force: yes
      become_user: ec2-user

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_dir }}/frontend/requirements.txt"
        executable: pip3
      become_user: ec2-user

    - name: Create systemd service file
      template:
        src: pokeapi-frontend.service.j2
        dest: /etc/systemd/system/pokeapi-frontend.service
        
    - name: Enable and start frontend service
      systemd:
        name: pokeapi-frontend
        state: started
        enabled: yes
        daemon_reload: yes